### ISSUE TITLE
Segmentation fault with simple test

### ISSUE THREAD

**Issue by robert-reay** [ryanc414/pytest_runner#1]
Trying pytest_web_ui for the first time and I have been unable to get it to run..

Ubuntu 18 install in a VM I make a simple pipenv environment. I Install pytest, pytest_web_ui, and requests, and then make a simple test.

pytest runs as expected. 

pytest_web_ui it brings up an unlabeled webpage.  When I hit the run button it python segfaults.

<pre>(foo) <font color="#8AE234"><b>rob</b></font>:<font color="#729FCF"><b>~/foo</b></font>$ pytest_web_ui
<b>============================= test session starts ===========================</b>
<b>===</b>
platform linux -- Python 3.8.0, pytest-5.4.3, py-1.9.0, pluggy-0.13.1
rootdir: /home/rob/foo
<b>collected 1 item                                                               </b>

&lt;Module test_sample.py&gt;
  &lt;Function test_answer&gt;

<font color="#4E9A06">============================ </font><font color="#C4A000">no tests ran</font><font color="#4E9A06"> in 0.00s =======</font>
<font color="#4E9A06">======================</font>
CRITICAL:pytest_web_ui.__main__:View in your browser at http://localhost:5000/
<b>============================= test session starts ===========================</b>
<b>===</b>
platform linux -- Python 3.8.0, pytest-5.4.3, py-1.9.0, pluggy-0.13.1
rootdir: /home/rob/foo
<b>collected 1 item                                                               </b>

test_sample.py <font color="#CC0000">F</font>Fatal Python error: Segmentation fault

Current thread 0x00007fa244692740 (most recent call first):
  File &quot;/usr/lib/python3.8/multiprocessing/queues.py&quot;, line 83 in put
  File &quot;/home/rob/.local/share/virtualenvs/foo-ksblnuCH/lib/python3.8/site-packa
ges/pytest_web_ui/runner.py&quot;, line 198 in pytest_runtest_logreport
  File &quot;/home/rob/.local/share/virtualenvs/foo-ksblnuCH/lib/python3.8/site-packa
ges/pluggy/callers.py&quot;, line 187 in _multicall
  File &quot;/home/rob/.local/share/virtualenvs/foo-ksblnuCH/lib/python3.8/site-packa
ges/pluggy/manager.py&quot;, line 84 in &lt;lambda&gt;
  File &quot;/home/rob/.local/share/virtualenvs/foo-ksblnuCH/lib/python3.8/site-packa
ges/pluggy/manager.py&quot;, line 93 in _hookexec
  File &quot;/home/rob/.local/share/virtualenvs/foo-ksblnuCH/lib/python3.8/site-packa
ges/pluggy/hooks.py&quot;, line 286 in __call__
  File &quot;/home/rob/.local/share/virtualenvs/foo-ksblnuCH/lib/python3.8/site-packa
ges/_pytest/runner.py&quot;, line 190 in call_and_report
  File &quot;/home/rob/.local/share/virtualenvs/foo-ksblnuCH/lib/python3.8/site-packa
ges/_pytest/runner.py&quot;, line 100 in runtestprotocol
  File &quot;/home/rob/.local/share/virtualenvs/foo-ksblnuCH/lib/python3.8/site-packa
ges/_pytest/runner.py&quot;, line 85 in pytest_runtest_protocol
  File &quot;/home/rob/.local/share/virtualenvs/foo-ksblnuCH/lib/python3.8/site-packa
ges/pluggy/callers.py&quot;, line 187 in _multicall
  File &quot;/home/rob/.local/share/virtualenvs/foo-ksblnuCH/lib/python3.8/site-packa
ges/pluggy/manager.py&quot;, line 84 in &lt;lambda&gt;
  File &quot;/home/rob/.local/share/virtualenvs/foo-ksblnuCH/lib/python3.8/site-packa
ges/pluggy/manager.py&quot;, line 93 in _hookexec
  File &quot;/home/rob/.local/share/virtualenvs/foo-ksblnuCH/lib/python3.8/site-packa
ges/pluggy/hooks.py&quot;, line 286 in __call__
  File &quot;/home/rob/.local/share/virtualenvs/foo-ksblnuCH/lib/python3.8/site-packa
ges/_pytest/main.py&quot;, line 272 in pytest_runtestloop
  File &quot;/home/rob/.local/share/virtualenvs/foo-ksblnuCH/lib/python3.8/site-packa
ges/pluggy/callers.py&quot;, line 187 in _multicall
  File &quot;/home/rob/.local/share/virtualenvs/foo-ksblnuCH/lib/python3.8/site-packa
ges/pluggy/manager.py&quot;, line 84 in &lt;lambda&gt;
  File &quot;/home/rob/.local/share/virtualenvs/foo-ksblnuCH/lib/python3.8/site-packa
ges/pluggy/manager.py&quot;, line 93 in _hookexec
  File &quot;/home/rob/.local/share/virtualenvs/foo-ksblnuCH/lib/python3.8/site-packa
ges/pluggy/hooks.py&quot;, line 286 in __call__
  File &quot;/home/rob/.local/share/virtualenvs/foo-ksblnuCH/lib/python3.8/site-packa
ges/_pytest/main.py&quot;, line 247 in _main
  File &quot;/home/rob/.local/share/virtualenvs/foo-ksblnuCH/lib/python3.8/site-packa
ges/_pytest/main.py&quot;, line 191 in wrap_session
  File &quot;/home/rob/.local/share/virtualenvs/foo-ksblnuCH/lib/python3.8/site-packa
ges/_pytest/main.py&quot;, line 240 in pytest_cmdline_main
  File &quot;/home/rob/.local/share/virtualenvs/foo-ksblnuCH/lib/python3.8/site-packa
ges/pluggy/callers.py&quot;, line 187 in _multicall
  File &quot;/home/rob/.local/share/virtualenvs/foo-ksblnuCH/lib/python3.8/site-packa
ges/pluggy/manager.py&quot;, line 84 in &lt;lambda&gt;
  File &quot;/home/rob/.local/share/virtualenvs/foo-ksblnuCH/lib/python3.8/site-packa
ges/pluggy/manager.py&quot;, line 93 in _hookexec
  File &quot;/home/rob/.local/share/virtualenvs/foo-ksblnuCH/lib/python3.8/site-packa
ges/pluggy/hooks.py&quot;, line 286 in __call__
  File &quot;/home/rob/.local/share/virtualenvs/foo-ksblnuCH/lib/python3.8/site-packa
ges/_pytest/config/__init__.py&quot;, line 124 in main
  File &quot;/home/rob/.local/share/virtualenvs/foo-ksblnuCH/lib/python3.8/site-packa
ges/pytest_web_ui/runner.py&quot;, line 100 in _run_test
  File &quot;/usr/lib/python3.8/multiprocessing/process.py&quot;, line 108 in run
  File &quot;/usr/lib/python3.8/multiprocessing/process.py&quot;, line 313 in _bootstrap
  File &quot;/usr/lib/python3.8/multiprocessing/spawn.py&quot;, line 129 in _main
  File &quot;/usr/lib/python3.8/multiprocessing/spawn.py&quot;, line 116 in spawn_main
  File &quot;&lt;string&gt;&quot;, line 1 in &lt;module&gt;
^C
(foo) <font color="#8AE234"><b>rob</b></font>:<font color="#729FCF"><b>~/foo</b></font>$ 
</pre>

![Screenshot from 2020-07-21 16-18-53](https://user-images.githubusercontent.com/10199045/88103339-dc3c4580-cb6e-11ea-84af-6781aa0532cc.png)

**Comment by ryanc414** [comment]
Sorry for the very delayed response, I've only just seen this issue. Thanks for raising!

Getting a segfault in python is quite unusual! I'm pretty sure it must be caused by this issue in the multiprocessing library: https://bugs.python.org/issue33196

Essentially, I was using the "Spawn" context of the multiprocessing library to spawn new processes, however I was using the default context to create Queue objects passed to the child processes. On macOS the default context is "Spawn" so there is no issue, however on Linux the default context is "Fork" and using a Fork-compatible Queue with a Spawn Process does not work.

This would have been inadvertantly fixed when I dropped the explicit use of the spawn context when creating new Process objects: https://github.com/ryanc414/pytest_commander/commit/e0cf1393ad370d5b01dfe3ed01bbae5df5e379bf#diff-3e232f2c6ddc1145cf98e18c22b36a78L88 . If you are still interested in the project now would be a good time to try again, as I have made a bunch of improvements in the latest V2 release.
