### ISSUE TITLE
python 3.6 support - "from future import annotations"

### ISSUE THREAD

**Issue by Pcb21** [ryanc414/pytest_runner#11]
I installed version 2.3.1 under Python 3.6, but on running a command line with no arguments (i.e. c:\myproject:> pytest_commander) I get an import failure:

```
File "c:\python\python36\lib\site-packages\pytest_commander\__main__py", line 11
   from pytest_commander import api
File "c:\python\python36\lib\site-packages\pytest_commander\api.py", line 11
   from pytest_commander import runner
File "c:\python\python36\lib\site-packages\pytest_commander\runner.py", line 24
   from pytest_commander import result_tree
File "c:\python\python36\lib\site-packages\pytest_commander\result_tree.py", line 7
   from __future__ import annotations

SyntaxError: future feature annotations is not defined
```
This makes sense because delayed evaluation of annotations wasn't introduced as a future feature until 3.7. However currently you are advertising (e.g. on pypi.org) support 3.6+. I am interested to know if you plan to support 3.6 or you are 3.7+ only these days? If so, is there an older version you would recommend for 3.6 users? 

Many thanks.

**Comment by ryanc414** [comment]
Hi, thanks for raising this! I didn't realise that the `__future__` annotations were not available in 3.6, I've removed the dependency on that feature in the latest v2.4.0 release so please give that a try.

**Comment by Pcb21** [comment]
Hi Ryan. Thanks so much for the quick change. (For what's its worth, I also got confused by annotations arriving both as feature and a future feature in 3.7!). The good news is that with 2.4.0 I get past that error with Python 3.6.

The less good news is that when my browser opens it says on the "loading" screen. Looking into the developer tools (in Chrome) it shows that "api/v1/result-tree" is returning 500 (INTERNAL SERVER ERROR) over-and-over. I don't whether this could be a 3.6 issue or some setup issue on my side. If you have tips for how to debug it, please let me know (or if you prefer we open a new issue). Thanks again for your help.

![internal error](https://user-images.githubusercontent.com/44731120/106432862-3778ba00-6467-11eb-8a46-6b78fb9af7ef.PNG)

**Comment by ryanc414** [comment]
> Hi Ryan. Thanks so much for the quick change. (For what's its worth, I also got confused by annotations arriving both as feature and a future feature in 3.7!). The good news is that with 2.4.0 I get past that error with Python 3.6.
> 
> The less good news is that when my browser opens it says on the "loading" screen. Looking into the developer tools (in Chrome) it shows that "api/v1/result-tree" is returning 500 (INTERNAL SERVER ERROR) over-and-over. I don't whether this could be a 3.6 issue or some setup issue on my side. If you have tips for how to debug it, please let me know (or if you prefer we open a new issue). Thanks again for your help.
> 
> ![internal error](https://user-images.githubusercontent.com/44731120/106432862-3778ba00-6467-11eb-8a46-6b78fb9af7ef.PNG)

hmm not sure why you are getting that, I definitely tested with python 3.6.12 after removing the annotations dependence and it appeared to work for me. Do you have any error output in the terminal where you are running pytest_commander?

**Comment by Pcb21** [comment]
No output, I'm afraid. I was running it on a fairly large existing pytest-ed code base inside a corporate environment. I will try to thin it down to something simpler and hopefully that will pinpoint the issue.

Thanks.

**Comment by ryanc414** [comment]
No worries, corporate environments can be tricky sometimes...

I'll look into why the 500 server errors aren't being logged in the console, they definitely should be.

There might be some conflict between the dependencies of this package with those of your codebase, `pip freeze` output would be helpful.

**Comment by Pcb21** [comment]
Thanks Ryan. You were right on the money expecting a dependencies problem. 

I already had flask and Werkzeug in this env . I force-upgraded them and the problem went away. In case of interest, the version change was 0.16.1 => 1.0.1 for Werkzeug and 1.0.2 => 1.1.2 for Flask.

**Comment by ryanc414** [comment]
OK great glad you worked it out! I've been quite lazy in terms of pinning version requirements, I should probably make them a bit stricter so that pip is hopefully able to install the correct version automatically.

**Comment by ryanc414** [comment]
Dependencies are tightened up in the latest release and errors should now be logged to the terminal even when not in debug mode now.
