### ISSUE TITLE
raise RuntimeError(f"Failed to collect tests from {entry.path}")

### ISSUE THREAD

**Issue by niroshaimos** [ryanc414/pytest_runner#2]
Hi, I'm having a bit of trouble using the tool.
When I try to run the pytest_web_ui like so: 'python3 -m pytest_web_ui {path_to_my_project_folder}'
I get an error message: Failed to collect tests from {path_to_my_project_folder}/conftest.py
I can't figure out why it's searching in conftest.py for tests.
The project contains 6 tests in a file named test_program not in a class.
I have no idea why this happens.. Any help will be very much appreciated. Thanks in advance.

**Comment by ryanc414** [comment]
Hi, thanks for raising this issue. It should be fixed in the latest 1.3.0 release, please try updating to the latest version with `pip install --upgrade pytest-web-ui`
